service: Koia-serverless-demo

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  profile: koia-role
  region: ${env:REGION}
  timeout: 30
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource: ${env:ARN_S3_BUCKET}
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
          Resource: ${env:ARN_S3_BUCKET}/*

  environment:
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    S3_BUCKET_URL: {env:S3_BUCKET_URL}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
